version: '2'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes: 
      - ./frontend:/code
    command: bash -c "npm run start"
    ports: 
      - 3001:3001
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes: 
      - ./backend:/code
    command: bash -c "node app.js"
    ports: 
      - 3000:3000
    depends_on: 
      - db
  db:
    image: mongo
    restart: always
    logging: 
      driver: none
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"